name: CraftPack
version: 1.3.8
description: Plugin for managing our server Resource Pack.
author: MrWakeCZ
main: cz.craftmania.craftpack.Main
api-version: "1.16"
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.5.21"
